export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const PROFILE_INFO_LOADING = "PROFILE_INFO_LOADING";
export const PROFILE_INFO_SUCCESS = "PROFILE_INFO_SUCCESS";
export const PROFILE_INFO_FAILED = "PROFILE_INFO_FAILED";
export const PROFILE_EDIT_LOADING = "PROFILE_EDIT_LOADING";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_FAILED = "PROFILE_EDIT_FAILED";

export const TASKS_LOADING = "TASKS_LOADING";
export const TASKS_SUCCESS = "TASKS_SUCCESS";
export const TASKS_FAILED = "TASKS_FAILED";

export const ERROR_PUSH = "ERROR_PUSH";
export const ERROR_CANCEL = "ERROR_CANCEL";
