// ACTION CONSTANTS
// AUTH
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// PROFILE
export const PROFILE_INFO_LOADING = "PROFILE_INFO_LOADING";
export const PROFILE_INFO_SUCCESS = "PROFILE_INFO_SUCCESS";
export const PROFILE_INFO_FAILED = "PROFILE_INFO_FAILED";
export const PROFILE_EDIT_LOADING = "PROFILE_EDIT_LOADING";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_FAILED = "PROFILE_EDIT_FAILED";

// TASKS
export const TASK_LOADING = "TASKS_LOADING";
export const TASK_FAILED = "TASKS_FAILED";
export const TASK_GET_SUCCESS = "TASKS_SUCCESS";
export const TASK_ADD_SUCCESS = "TASK_ADD_SUCCESS";
export const TASK_TOGGLE_COMPLETION_SUCCESS =
	"TASK_TOGGLE_COMPLETION_SUCCESS";

// PRODUCTS
export const PRODUTS_LOADING = "PRODUCTS_LOADING";
export const PRODUTS_SUCCESS = "PRODUCTS_SUCCESS";
export const PRODUTS_FAILED = "PRODUCTS_FAILED";

// ERROR
export const ERROR_PUSH = "ERROR_PUSH";
export const ERROR_CANCEL = "ERROR_CANCEL";
